server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/seal?useUnicode=true&characterEncoding=utf-8&useSSL=false 
    username : root
    password : admin
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    host: 172.0.0.1
    password: wbtest
    port: 6379
    pool:
      maxTotal: 10
      max-idle: 5
      maxWaitMillis: 1000
      testOnBorrow: true
# Mybatis配置
mybatis:
  typeAliasesPackage: com.compilespace.domain
  mapperLocations: classpath:com/compilespace/dao/mapper/*.xml

    
    
      
      

     